# Generated by Django 4.2.2 on 2023-06-23 06:06

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera_show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Camera_Image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='CameraI')),
                ('Camera_About', models.CharField(max_length=50)),
            ],
        ),
    ]
