# Generated by Django 4.2.2 on 2023-06-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_alter_camera_show_camera_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=80)),
                ('Email', models.EmailField(max_length=180)),
                ('Subject', models.CharField(max_length=180)),
                ('Masg', models.CharField(max_length=2000)),
            ],
        ),
    ]
