# Generated by Django 4.2.2 on 2023-06-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_contact_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Password', models.IntegerField()),
            ],
        ),
    ]
