# Generated by Django 4.2.2 on 2023-06-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_signup_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestions_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Phone', models.BigIntegerField()),
                ('Email', models.EmailField(max_length=50)),
                ('Topic', models.TextField(max_length=60)),
                ('Misg', models.TextField(max_length=2000)),
            ],
        ),
    ]
