# Generated by Django 4.2.2 on 2023-06-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0005_suggestions_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='login_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField(max_length=50)),
                ('User_password', models.BigIntegerField()),
            ],
        ),
    ]
