# Generated by Django 4.2.2 on 2023-06-26 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0006_login_form'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login_form',
        ),
    ]
